/* --- HUONG DAN SU DUNG SCFOOD --- */
const SCF_GUIDES={
  accounting:{label:'Kế toán',icon:'ti-calculator',intro:'Quản lý đơn hàng, chuyến giao, hóa đơn, công nợ và các yêu cầu cần duyệt.',sections:[
    {title:'Kiểm tra và cập nhật đơn hàng',steps:['Vào Bán hàng → Đơn giao hàng. Chọn đúng ngày hoặc tháng cần làm việc.','Kiểm tra khách hàng, địa điểm, sản phẩm, số lượng hóa đơn và giờ giao.','Dùng nút Sửa để cập nhật; mọi thay đổi đều được lưu tại nút Lịch sử.','Bấm Cập nhật SX + chuyến khi cần tính lại ca sản xuất và chuyến giao tự động.'],note:'Không sửa trực tiếp đơn đã giao hoàn thành nếu chưa kiểm tra hóa đơn và công nợ liên quan.'},
    {title:'Xếp chuyến và giao chuyến cho lái xe',steps:['Vào Bán hàng → Chuyến giao hàng và chọn ngày giao.','Tạo chuyến từ đúng Ca giao hàng; kiểm tra danh sách đơn trong chuyến.','Chọn lái xe, sau đó bấm Giao lái xe. Chỉ lúc này lái xe mới nhìn thấy chuyến.','Khi thêm hoặc bỏ đơn khỏi chuyến đã giao, lái xe sẽ nhận thông báo tự động.'],note:'Nếu đổi lái xe, kiểm tra lại tên người nhận chuyến trước khi lưu.'},
    {title:'Duyệt đơn phát sinh của lái xe',steps:['Khi lái xe tạo đơn phát sinh, kế toán nhận thông báo Có đơn phát sinh cần duyệt.','Mở Thông báo hoặc Chuyến giao hàng, mở chi tiết chuyến tương ứng.','Kiểm tra khách hàng, địa điểm, sản phẩm và số lượng.','Bấm Duyệt đơn. Lái xe sẽ nhận thông báo xác nhận.'],note:'Chuyến không thể hoàn thành khi đơn phát sinh còn ở trạng thái chờ duyệt.'},
    {title:'Duyệt hoàn thành chuyến và hóa đơn',steps:['Mở chuyến ở trạng thái Chờ kế toán duyệt.','Kiểm tra số thực giao, ảnh hóa đơn từng đơn và hóa đơn tổng chuyến.','Duyệt hoặc trả lại từng hóa đơn kèm lý do rõ ràng.','Khi đầy đủ, bấm Kế toán duyệt để hoàn thành chuyến và ghi nhận công nợ.'],note:'Số thực giao dùng tính doanh thu; số hóa đơn dùng tính công nợ theo thiết lập hiện tại.'},
    {title:'Theo dõi lịch sử và thông báo',steps:['Bấm biểu tượng chuông để xem các việc mới phát sinh.','Bấm Lịch sử tại mỗi đơn để xem ai tạo, ai sửa, thời gian và nội dung cũ → mới.','Đánh dấu đã đọc sau khi xử lý xong.','Có thể bật thông báo trên thiết bị để nhận cảnh báo khi webapp đang mở hoặc chạy nền.']}
  ]},
  attendance:{label:'Nhân viên chấm công',icon:'ti-fingerprint',intro:'Chấm công, gửi đơn nghỉ phép và theo dõi các thông tin cá nhân.',sections:[
    {title:'Chấm công vào và ra',steps:['Đăng nhập đúng tài khoản cá nhân, vào Quản lý nhân sự → Chấm công.','Bấm Chấm công vào khi bắt đầu làm việc.','Cuối ca bấm Chấm công ra và kiểm tra thời gian hiển thị.','Nếu hệ thống yêu cầu vị trí hoặc ảnh xác nhận, cấp quyền và thực hiện theo hướng dẫn trên màn hình.'],note:'Không chấm công hộ. Mỗi tài khoản chỉ ghi nhận cho chính nhân viên đang đăng nhập.'},
    {title:'Kiểm tra bảng công',steps:['Vào Báo công → Báo cáo chấm công.','Chọn tháng cần kiểm tra.','Đối chiếu ngày làm, giờ vào, giờ ra, đi muộn hoặc về sớm.','Nếu có sai sót, báo quản lý và nêu rõ ngày, ca làm việc cần điều chỉnh.']},
    {title:'Gửi yêu cầu nghỉ phép',steps:['Vào Quản lý nhân sự → Xin nghỉ.','Chọn ngày bắt đầu, ngày kết thúc và loại nghỉ.','Nhập lý do đầy đủ rồi gửi yêu cầu.','Theo dõi trạng thái Chờ duyệt, Đã duyệt hoặc Từ chối.'],note:'Nên gửi yêu cầu trước ngày nghỉ, trừ trường hợp đột xuất.'},
    {title:'Nhận và báo cáo công việc',steps:['Vào Giao việc hoặc mở thông báo mới.','Đọc nội dung, thời hạn và yêu cầu chất lượng.','Cập nhật tiến độ theo đúng trạng thái thực tế.','Khi hoàn thành, gửi báo cáo và minh chứng nếu công việc yêu cầu.']}
  ]},
  production:{label:'Nhân viên sản xuất',icon:'ti-building-factory-2',intro:'Theo dõi kế hoạch sản xuất, thực hiện đúng ca, cập nhật sản lượng và xử lý thay đổi đơn hàng.',sections:[
    {title:'Xem kế hoạch sản xuất trong ca',steps:['Đăng nhập đúng tài khoản cá nhân và vào Sản xuất → Đơn sản xuất hoặc Tổng hợp sản xuất.','Chọn đúng ngày sản xuất và ca làm việc.','Kiểm tra từng sản phẩm, tổng số lượng cần sản xuất, giờ hoàn thành và giờ in tem.','Ưu tiên các đơn có giờ giao sớm; đối chiếu lại khi có thông báo thay đổi đơn.'],note:'Ngày sản xuất có thể khác ngày giao hàng. Luôn làm theo Ngày SX và Giờ SX hiển thị trên kế hoạch.'},
    {title:'Kiểm tra nguyên liệu và chuẩn bị sản xuất',steps:['Xem danh sách sản phẩm và sản lượng của ca.','Đối chiếu định mức hoặc quy trình sản xuất tương ứng: bún, phở, bánh cuốn hoặc sản phẩm khác.','Kiểm tra nguyên liệu, bao bì, tem và thiết bị trước khi bắt đầu.','Nếu thiếu nguyên liệu hoặc thiết bị có sự cố, báo quản lý ngay trước khi sản xuất.'],note:'Không tự ý thay đổi định mức, sản phẩm hoặc số lượng đơn hàng trên kế hoạch.'},
    {title:'Thực hiện và cập nhật sản lượng',steps:['Mở đúng đơn sản xuất đang thực hiện.','Nhập sản lượng thực tế sau mỗi mẻ hoặc sau khi hoàn thành theo quy định của bộ phận.','Ghi chú rõ hàng lỗi, hao hụt, sản xuất bổ sung hoặc nguyên nhân chênh lệch.','Kiểm tra lại tổng thực tế trước khi xác nhận hoàn thành.'],note:'Sản lượng thực tế phải phản ánh đúng số lượng đạt chất lượng, không tính hàng lỗi.'},
    {title:'In tem và bàn giao hàng',steps:['Kiểm tra tên sản phẩm, địa điểm, ngày sản xuất và số lượng trước khi in tem.','In tem theo thời gian hiển thị trên kế hoạch; dán đúng sản phẩm và đúng khách hàng.','Sắp xếp hàng theo khu vực/chuyến giao để tránh giao nhầm.','Bàn giao cho kho hoặc lái xe và xác nhận số lượng thực tế bàn giao.']},
    {title:'Xử lý đơn thay đổi hoặc phát sinh',steps:['Khi kế toán sửa đơn hoặc thêm đơn vào chuyến, kiểm tra thông báo và tải lại kế hoạch.','Đối chiếu phần số lượng, sản phẩm, giờ giao và ca sản xuất đã thay đổi.','Chỉ sản xuất bổ sung sau khi đơn đã được kế toán xác nhận.','Nếu không đủ thời gian hoàn thành, báo ngay cho quản lý và kế toán để điều chỉnh phương án giao.'],note:'Không sản xuất theo tin nhắn miệng nếu đơn chưa xuất hiện hoặc chưa được duyệt trên hệ thống.'},
    {title:'Kết thúc ca và báo cáo',steps:['Kiểm tra tất cả đơn trong ca đã được cập nhật sản lượng.','Ghi nhận hàng tồn, hàng lỗi, nguyên liệu còn lại và các sự cố trong ca.','Hoàn thành công việc được giao và gửi báo cáo nếu có.','Chấm công ra sau khi đã bàn giao công việc cho ca tiếp theo hoặc quản lý.']},
    {title:'Các lỗi thường gặp',steps:['Không thấy kế hoạch: kiểm tra đúng ngày, đúng ca và tải lại trang.','Số lượng không khớp: kiểm tra đơn vừa được kế toán thay đổi hay chưa đồng bộ.','Tên sản phẩm cũ: báo Admin thực hiện Cập nhật tên SP.','Không lưu được sản lượng: kiểm tra quyền tài khoản và trạng thái đồng bộ ở đầu màn hình.']}
  ]},
  driver:{label:'Lái xe',icon:'ti-steering-wheel',intro:'Nhận chuyến, giao hàng, cập nhật số thực giao, hóa đơn và đơn phát sinh.',sections:[
    {title:'Nhận và bắt đầu chuyến',steps:['Mở Thông báo hoặc Bán hàng → Chuyến giao hàng.','Bạn chỉ nhìn thấy chuyến đã được giao đúng cho tài khoản của mình.','Mở chi tiết, kiểm tra ngày, ca giao, danh sách điểm và thứ tự giao.','Bấm Bắt đầu giao trước khi nhập kết quả giao hàng.'],note:'Nếu chuyến, địa điểm hoặc hàng hóa không đúng, báo kế toán trước khi xuất phát.'},
    {title:'Giao hàng và nhập số thực giao',steps:['Mở từng đơn trong chi tiết chuyến.','Nhập SL Giao đúng với số khách hàng thực nhận.','Chụp hoặc tải ảnh hóa đơn của từng đơn.','Theo dõi trạng thái kế toán duyệt; nếu bị trả lại, đọc lý do và tải ảnh mới.']},
    {title:'Tạo đơn phát sinh',steps:['Chỉ trong chuyến đang giao, bấm + Đơn phát sinh.','Chọn khách hàng, địa điểm, sản phẩm và nhập số lượng. Có thể thêm nhiều sản phẩm vào một đơn.','Bấm Gửi kế toán duyệt. Đơn được đưa ngay vào chuyến với nhãn Chờ kế toán duyệt.','Chờ thông báo kế toán đã duyệt rồi tiếp tục giao và nhập số thực giao.'],note:'Mỗi chuyến chỉ được tạo tối đa 1 đơn phát sinh và không thể hoàn thành chuyến khi đơn chưa được duyệt.'},
    {title:'Hoàn thành chuyến',steps:['Kiểm tra tất cả dòng hàng đã có số thực giao.','Đảm bảo mỗi đơn có ảnh hóa đơn và chuyến có hóa đơn tổng.','Bấm Giao hoàn thành.','Chuyến được chuyển sang kế toán duyệt; theo dõi thông báo nếu có nội dung bị trả lại.']},
    {title:'Xử lý sự cố',steps:['Mất mạng: tiếp tục giữ webapp, chờ trạng thái đồng bộ trở lại rồi kiểm tra dữ liệu.','Không thấy chuyến: kiểm tra đúng tài khoản hoặc liên hệ kế toán bấm Giao lái xe.','Không tạo được đơn phát sinh: chuyến chưa bắt đầu hoặc đã có một đơn phát sinh.','Không hoàn thành được: đọc danh sách điều kiện còn thiếu hiển thị cuối chi tiết chuyến.']}
  ]}
};

function UserGuideTab({currentUser}){
  const dept=String(currentUser?.dept||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const isProduction=dept.includes('san xuat')||dept.includes('bep')||dept.includes('dong goi')||dept.includes('che bien');
  const defaultRole=currentUser?.role==='driver'?'driver':dept.includes('ke toan')?'accounting':isProduction?'production':'attendance';
  const canViewAll=currentUser?.role==='admin';
  const allowedRoles=canViewAll?Object.keys(SCF_GUIDES):[defaultRole];
  const[role,setRole]=useState(defaultRole);const[q,setQ]=useState('');
  useEffect(()=>{if(!allowedRoles.includes(role)){setRole(defaultRole);setQ('');}},[defaultRole,currentUser?.id]);
  const guide=SCF_GUIDES[role];const query=String(q||'').trim().toLowerCase();
  const sections=guide.sections.filter(s=>!query||[s.title,s.note,...s.steps].some(v=>String(v||'').toLowerCase().includes(query)));
  return h('div',{className:'guide-page'},
    h('div',{className:'guide-hero'},h('div',null,h('div',{className:'ptitle'},h('i',{className:'ti ti-book-2'}),'HDSD SCFOOD'),h('p',null,'Hướng dẫn thao tác theo từng vị trí công việc trong hệ thống.')),h('div',{className:'guide-search'},h('i',{className:'ti ti-search'}),h('input',{value:q,onChange:e=>setQ(e.target.value),placeholder:'Tìm nội dung hướng dẫn...'}))),
    canViewAll&&h('div',{className:'guide-role-tabs'},allowedRoles.map(key=>{const item=SCF_GUIDES[key];return h('button',{key,className:role===key?'on':'',onClick:()=>{setRole(key);setQ('');}},h('i',{className:'ti '+item.icon}),item.label);})),
    h('div',{className:'guide-intro'},h('i',{className:'ti '+guide.icon}),h('div',null,h('b',null,'Hướng dẫn dành cho '+guide.label),h('span',null,guide.intro))),
    h('div',{className:'guide-sections'},sections.length?sections.map((section,index)=>h('details',{key:section.title,className:'guide-section',open:index===0},h('summary',null,h('span',{className:'guide-number'},index+1),h('b',null,section.title),h('i',{className:'ti ti-chevron-down'})),h('div',{className:'guide-section-body'},h('ol',null,section.steps.map((step,i)=>h('li',{key:i},step))),section.note&&h('div',{className:'guide-note'},h('i',{className:'ti ti-alert-circle'}),h('span',null,h('b',null,'Lưu ý: '),section.note))))):h('div',{className:'empty-st',style:{padding:45}},'Không tìm thấy nội dung hướng dẫn phù hợp.'))
  );
}
